### ISSUE TITLE
Question regarding examples

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/XChem-examples#1]
Hi @reskyner,

clearly, my brain went a bit mush, you are ok with a simple example of a script that can run a parametrisation, equilibration and production run or something along those lines right? It doesn't have to be a full-blown free energy calculation or the like yet right?

Toni

**Comment by reskyner** [comment]
Hi @ppxasjsm,

That should be fine for now - free energy calculations eventually, but integrating anything at this point (our problem, of course) would be great.  

I've been off sick this week (is Scottish flu a thing?), but I'll aim to get some data up there as soon as possible. 

I'll also add the guys that write the workflow tools at some point, when I've had a chance to go through everything with them. 

Sorry for the delay!
Rachael

**Comment by ppxasjsm** [comment]
I have now added a commandline example you can work with in the directory solvation. Let me know if you run into any issues getting it to work. 

For sure you will need to have Gromacs and Ambertools installed as dependencies otherwise you'll get errors but other than that it should just work fine. You should also be able to play around with different input files, using your small molecules or one of the protein ones you have talked about and just choose appropriate forcefield options either as gaff (for small molecule) or e.g. ff14SB for a protein. The help will give you all available forcefields that are currently supported.

**Comment by jmichel80** [comment]
Ok that's a sensible place to start. I will help @reskyner get a FEP pipeline up and running once she can run BioSimSpace and associated dependencies in her environment.
